### ISSUE TITLE
LoopingCall and DeferLater no longer accept non-function callables

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10235]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#10235|
|Type|release blocker: regression|
|Created|2021-07-22 16:28:00Z|

introduced in https://github.com/twisted/twisted/commit/c902ced7a7e7c955090c7bc30e6d7793025390f2

PR https://github.com/twisted/twisted/pull/1570/files

on Twisted-21.2.0-py3-none-any.whl:
```
>>> from twisted.internet import task
>>> 
>>> class Foo:
...     def __call__(self):
...         print("hello")
... 
>>> task.LoopingCall(Foo())
LoopingCall<None>(<__main__.Foo object at 0x7ff93a5d4af0>, *(), **{})
```

<details><summary>Searchable metadata</summary>

```
trac-id__10235 10235
type__release_blocker__regression release blocker: regression
reporter__graingert graingert
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1626971280382296 1626971280382296
changetime__1627034361879550 1627034361879550
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)<a name="note_1"></a>|@graingert commented|
|-|-|

on Twisted-21.7.0rc2.tar.gz

```
>>> from twisted.internet import task
>>> 
>>> class Foo:
...     def __call__(self):
...         print("hello")
... 
>>> task.LoopingCall(Foo())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/.virtualenvs/tx38/lib/python3.8/site-packages/twisted/internet/task.py", line 298, in __repr__
    self.f.__qualname__,
AttributeError: 'Foo' object has no attribute '__qualname__'
```

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set status to `closed`|
|-|-|

PR at https://github.com/twisted/twisted/pull/1637
