### ISSUE TITLE
web http/wsgi doesn't fail gracefully when the client closes the connection

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9410]
|[<img alt="iksaif's avatar" src="https://avatars.githubusercontent.com/u/1032963?s=50" width="50" height="50">](https://github.com/iksaif)| @iksaif reported|
|-|-|
|Trac ID|trac#9410|
|Type|defect|
|Created|2018-04-04 08:02:35Z|

Assume a web view that does "sleep(10)" and a curl that you interrupt before the web page has been rendered, you'll get the following:

```
2018-04-03 17:37:43+0200 [-] WSGI application error
        Traceback (most recent call last):
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/python/context.py", line 87, in callWithContext
            self.contexts.pop()
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/web/wsgi.py", line 522, in run
            self.started = True
        --- <exception caught here> ---
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/web/wsgi.py", line 500, in run
            self.write(elem)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/web/wsgi.py", line 455, in write
            self.reactor, wsgiWrite, self.started)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
            result.raiseException()
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
            raise self.value.with_traceback(self.tb)
        builtins.AttributeError: 'NoneType' object has no attribute 'writeHeaders'

2018-04-03 17:37:43+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/flask_twisted/__init__.py", line 68, in run
            self.run_simple(app, host, port, **options)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/flask_twisted/__init__.py", line 46, in run_simple
            reactor.run()
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
            self.mainLoop()
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
            f(*a, **kw)
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/web/wsgi.py", line 510, in wsgiError
            self.request.loseConnection()
          File "/home/cchary/dev/jiralerts/venv/lib/python3.6/site-packages/twisted/web/http.py", line 1474, in loseConnection
            self.channel.loseConnection()
        builtins.AttributeError: 'NoneType' object has no attribute 'loseConnection'
```

Looking at the code, the reason is obvious:
```
    def connectionLost(self, reason):
        """
        There is no longer a connection for this request to respond over.
        Clean up anything which can't be useful anymore.
        """
        self._disconnected = True
        self.channel = None
        if self.content is not None:
            self.content.close()
        for d in self.notifications:
            d.errback(reason)
        self.notifications = []


    def loseConnection(self):
        """
        Pass the loseConnection through to the underlying channel.
        """
        self.channel.loseConnection()
```

connectionLost() will set self.channel to None, and loseConnection will still try to use the channel (I guess it should check if the channel is None or not).

<details><summary>Searchable metadata</summary>

```
trac-id__9410 9410
type__defect defect
reporter__iksaif iksaif
priority__highest highest
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1522828955875764 1522828955875764
changetime__1558100833528321 1558100833528321
version__None None
owner__jswitzer jswitzer

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

Looks like Buildbot has hit this as well: https://github.com/buildbot/buildbot/issues/4045

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

I am not marking this as a regression, because it's in the last release, but we've been seeing this traceback at work periodically with the 18.7 and did not see it previously, so I am bumping the priority (as if anyone pays attention to that) because I do think that this regressed, although I'm not sure exactly when.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Looks like _our_ buildbot is hitting this, with some regularity.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

https://buildbot.twistedmatrix.com/builders/osx10.11-py2.7-coverage/builds/350/steps/shell_5/logs/err.html

**Comment by twisted-trac** [comment]
|[<img alt="marcin-jedynski's avatar" src="https://avatars.githubusercontent.com/u/28704725?s=50" width="50" height="50">](https://github.com/marcin-jedynski)<a name="note_5"></a>|@marcin-jedynski commented|
|-|-|

Any news on resolution of this ?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

Replying to [Marcin Jedynski](#note_5):
> Any news on resolution of this ?

None yet, although I'd certainly love it if there were.

Would you have any interest in submitting a patch? :)

**Comment by twisted-trac** [comment]
|[<img alt="marcin-jedynski's avatar" src="https://avatars.githubusercontent.com/u/28704725?s=50" width="50" height="50">](https://github.com/marcin-jedynski)<a name="note_7"></a>|@marcin-jedynski commented|
|-|-|

Replying to [Glyph](#note_6):
> Replying to [Marcin Jedynski](#note_5):
> > Any news on resolution of this ?
> 
> None yet, although I'd certainly love it if there were.
> 
> Would you have any interest in submitting a patch? :)

Well I'm going through my last month of university, after that I would love to get involved in some open source projects so who knows :)

**Comment by twisted-trac** [comment]
|[<img alt="marcin-jedynski's avatar" src="https://avatars.githubusercontent.com/u/28704725?s=50" width="50" height="50">](https://github.com/marcin-jedynski)<a name="note_8"></a>|@marcin-jedynski commented|
|-|-|

For sure not within a month from now :)

**Comment by twisted-trac** [comment]
|[<img alt="jswitzer's avatar" src="https://avatars.githubusercontent.com/u/1204555?s=50" width="50" height="50">](https://github.com/jswitzer)<a name="note_9"></a>|@jswitzer commented|
|-|-|

I'm seeing a similar traceback after upgrading from 15.4 to the latest twisted. 
```
Jan  8 10:24:15 svc python: File "/root/.pyenv/versions/http_configurator/lib/python2.7/site-packages/twisted/web/server.py", line 238, in write
Jan  8 10:24:15 svc python: http.Request.write(self, data)
Jan  8 10:24:15 svc python: File "/root/.pyenv/versions/http_configurator/lib/python2.7/site-packages/twisted/web/http.py", line 1139, in write
Jan  8 10:24:15 svc python: self.channel.write(data)
Jan  8 10:24:15 svc python: exceptions.AttributeError: 'NoneType' object has no attribute 'write'
```


I see a bunch of queueing-related code was removed at some point. 

I'd hazard a guess at the change (I am not familiar with this code - so please take this with a grain of salt - I haven't had time to fully validate this hypothesis): 

- the old behavior was that writing a response to a request with a client that had vanished was OK as long as it was queued (the response going to a string buffer somewhere). Later, when request.finish() was called we'd see the familiar "Request.finish called on a request after its connection was lost" runtime error. This was because self.transport was set to this StringTransport object.

- the new behaviour is the Attribute error on self.channel (since self.transport is set to self.channel.transport and self.channel has been deleted).

Some fragments of the diff of src/twisted/web/http.py between trunk and 15.4 that led me to this conclusion: 
```
@@ -584,85 +713,33 @@                                                                                                                                                                                           
     content = None                                                                                                                                                                                             
     _forceSSL = 0                                                                                                                                                                                              
     _disconnected = False                                                                                                                                                                                      
+    _log = Logger()                                                                                                                                                                                            
                                                                                                                                                                                                                
-    def __init__(self, channel, queued):                                                                                                                                                                       
+    def __init__(self, channel, queued=_QUEUED_SENTINEL):                                                                                                                                                      
         """                                                                                                                                                                                                    
         @param channel: the channel we're connected to.                                                                                                                                                        
-        @param queued: are we in the request queue, or can we start writing to                                                                                                                                 
-            the transport?                                                                                                                                                                                     
+        @param queued: (deprecated) are we in the request queue, or can we                                                                                                                                     
+            start writing to the transport?                                                                                                                                                                    
         """                                                                                                                                                                                                    
         self.notifications = []                                                                                                                                                                                
         self.channel = channel                                                                                                                                                                                 
-        self.queued = queued                                                                                                                                                                                   
+                                                                                                                                                                                                               
+        # Cache the client and server information, we'll need this                                                                                                                                             
+        # later to be serialized and sent with the request so CGIs                                                                                                                                             
+        # will work remotely                                                                                                                                                                                   
+        self.client = self.channel.getPeer()                                                                                                                                                                   
+        self.host = self.channel.getHost()                                                                                                                                                                     
+                                                                                                                                                                                                               
         self.requestHeaders = Headers()                                                                                                                                                                        
         self.received_cookies = {}                                                                                                                                                                             
         self.responseHeaders = Headers()                                                                                                                                                                       
         self.cookies = [] # outgoing cookies                                                                                                                                                                   
+        self.transport = self.channel.transport                                                                                                                                                                
                                                                                                                                                                                                                
-        if queued:                                                                                                                                                                                             
-            self.transport = StringTransport()                                                                                                                                                                 
-        else:                                                                                                                                                                                                  
-            self.transport = self.channel.transport                                                                                                                                                            
-                                                                                                                                                                                                               
-   
```        

```

@@ -1018,31 +1130,113 @@
         self.sentLength = self.sentLength + len(data)
         if data:
             if self.chunked:
-                self.transport.writeSequence(toChunk(data))
+                self.channel.writeSequence(toChunk(data))
             else:
-                self.transport.write(data)
+                self.channel.write(data)
```

If this really is what is happening then I agree with Corentin that a few checks to see if self.channel is None will get rid of these tracebacks and defer the Runtime error to when .close is called. I'll put together a PR unless someone else gets to this first or tells me that something more subtle is going on here.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

Hi jswitzer!

Your analysis sounds vaguely correct; do you think you could write a unit test that validates this behavior?  (This is particularly interesting because we need to make sure it does the right thing on both HTTP/1.1 and HTTP/2.0.)

**Comment by twisted-trac** [comment]
|[<img alt="pryorda's avatar" src="https://avatars.githubusercontent.com/u/5644316?s=50" width="50" height="50">](https://github.com/pryorda)<a name="note_11"></a>|@pryorda commented|
|-|-|

This hit vmware_exporter as well. https://github.com/pryorda/vmware_exporter/issues/74

**Comment by twisted-trac** [comment]
|[<img alt="jswitzer's avatar" src="https://avatars.githubusercontent.com/u/1204555?s=50" width="50" height="50">](https://github.com/jswitzer)<a name="note_12"></a>|@jswitzer commented|
|-|-|

I created this PR: https://github.com/twisted/twisted/pull/1106

**Comment by twisted-trac** [comment]
|[<img alt="jswitzer's avatar" src="https://avatars.githubusercontent.com/u/1204555?s=50" width="50" height="50">](https://github.com/jswitzer)<a name="note_13"></a>|@jswitzer commented|
|-|-|

Can I ask for some help on my PR? AFAIK it's ready to go at the moment. Do I need to flag it somehow for a review?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun commented|
|-|-|

> Can I ask for some help on my PR? AFAIK it's ready to go at the moment. Do I need to flag it somehow for a review?

Yep.  Put the "review" keyword on the ticket.  See ReviewProcess.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_17"></a>|@exarkun commented|
|-|-|

Hello.  Thanks for your contribution.  Sorry about the delay in looking at it.  I've left a review on GitHub.  Unfortunately, I'm not really sure what we should do in this case so I've left a comment-only review (neither approving nor rejecting the PR).  The gist is that I'm not clear on whether request.write raising an exception is a bug we can fix or an intended behavior we need to preserve (or go through the incompatibility process to change).

I'll try and start a discussion about that question and then revisit this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun commented|
|-|-|

FWIW, it looks like a small and WSGI-focused fix would be along these lines:

```
diff --git a/src/twisted/web/wsgi.py b/src/twisted/web/wsgi.py
index 311050f23..65677934f 100644
--- a/src/twisted/web/wsgi.py
+++ b/src/twisted/web/wsgi.py
@@ -504,10 +504,10 @@ class _WSGIResponse:
         try:
             appIterator = self.application(self.environ, self.startResponse)
             for elem in appIterator:
-                if elem:
-                    self.write(elem)
                 if self._requestFinished:
                     break
+                if elem:
+                    self.write(elem)
             close = getattr(appIterator, 'close', None)
             if close is not None:
                 close()
```

The test in the linked PR doesn't tell us if this works or not though since it is at the level of `IRequest` behavior and this fix is in the WSGI implementation.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @jswitzer|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_22"></a>|@exarkun set status to `closed`|
|-|-|

In changeset c8d59d663964821af685c869627ac132d28ba0c5
```
#!CommitTicketReference repository="" revision="c8d59d663964821af685c869627ac132d28ba0c5"
Merge pull request #1106 from jswitzer/trunk

[9410] Don't throw KeyError exception on write to _disconnected http request

Author: jswitzer
Reviewer: exarkun
Fixes: ticket:9410
```
