### ISSUE TITLE
[PATCH]JellyToNode lacks support for boolean types in Python 2.3

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7594]
|<img alt="aubin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| aubin reported|
|-|-|
|Trac ID|trac#363|
|Type|defect|
|Created|2003-10-21 21:29:47Z|

Attachments:

* [filefile](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/15a/15a17abee2bf17c4859db0247500fc078d2a5dd4/c90ec4ab6fea6e24ab4bb458503403a55c79831c) (1385 bytes) - added by moshez on 2003-10-22 15:01:07Z - 
* [patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/15a/15a17abee2bf17c4859db0247500fc078d2a5dd4/d75b3b528276d7a9f30a04b8bccaf74e1d61f67a) (1216 bytes) - added by gclinch on 2004-04-09 03:58:24Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__363 363
type__defect defect
reporter__aubin aubin
priority__high high
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__pb pb
keywords__ 
time__1066771787000000 1066771787000000
changetime__1469028083140142 1469028083140142
version__ 
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="aubin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|aubin commented|
|-|-|

```
#!html
<pre>
It is currently not possible to serialize a boolean type using JellyToNode; attempts to do so result in 
this error:
        AttributeError: 'bool' object has no attribute '__dict__'

Boolean types do not exist before Python 2.3.

To fix it, something like this would need to be added to twisted.persisted.DOMJellier.JellyToNode:
--------------------------------------------
elif objType is types.BooleanTypes:
     node = self.document.createElement("int")
     node.setAttribute("value", int(obj))
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
Um, no, that's about the silliest solution ever. The proper solution
is to jelly to "bool" with 1/0, and then add a relevant line to
unjellyNode.

I'll try to write a patch this weekend.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Jelly has a boolean type (java pb supports it). The question is how to support
it in a 2.2 compatible way.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="aubin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|aubin commented|
|-|-|

```
#!html
<pre>
The reason I suggested changing the variable into an int was because I didn't want to make a 
suggestion that would break compatibility with Python 2.2. Currently, it would need to be wrapped 
in a sys.version check, which you probably wouldn't want to send all over the place. 

Either that, or defining the Boolean type explicitly if sys.version returns 2.2.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
Nah, pickles (and so jelly) have no intention to be forward compatible.
Changing types is not an option. If there's no boolean in the
target, it damn well should raise an exception.
Of course, that's an excellent reason to avoid pickling booleans.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Uh, no. That is not acceptable. Jelly needs to work on 2.2, and it needs to
support the full set of features, and it needs to be as transparent as possible
for python.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
Here's a patch to serialize it to &lt;bool> and to deserialize it to whatever 
1==1 and 1!=1 give, which will be "best approximation to boolean"
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="aubin's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|aubin commented|
|-|-|

```
#!html
<pre>
Looks good to me... thanks for your help.

Also, is this expected to be in the next release? The issue cropped up in a project I work on called 
Freevo and I just want to know how long to keep our workaround in place. No rush, of course, 
since we have a workaround.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
There's a bug party this weekend, and I'm hoping to integrate all bugs with
patches in them...
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)|@moshez commented|
|-|-|

```
#!html
<pre>
Itamar, please review and apply.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="gclinch's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|gclinch commented|
|-|-|

```
#!html
<pre>
The patch in msg1415 does not work in 1.2.1alpha; I get an exception deep inside microdom 
"exceptions.AttributeError, 'int' object has no attribute 'replace'".  The fix appears to be to wrap the 
call to int() in a str(), my alterations to the original patchfile are attached.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jerub's avatar" src="https://avatars.githubusercontent.com/u/315461?s=50" width="50" height="50">](https://github.com/jerub)|@jerub set status to `closed`|
|-|-|

This is fixed in r11503

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="GitHub's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_14"></a>|GitHub commented|
|-|-|

In changeset dfc3aaaa83353bb5201089af3907a70b5b4ea1a6
```
#!CommitTicketReference repository="" revision="dfc3aaaa83353bb5201089af3907a70b5b4ea1a6"
Merge pull request #363 from scop/8634-scop-closing

Author: scop
Reviewer: rodrigc
Fixes: #8634

In a few tests, close some files that were left open.
```
