### ISSUE TITLE
Upgrade mypy to 2.3.0 and resolve new issues

### ISSUE THREAD

**Issue by gudnimg** [twisted/twisted#12723]
**Is your feature request related to a problem? Please describe.**

When I upgrade `mypy` to 2.3.0 and `mypy-zope` to 1.0.16 I get this list of errors:

```
src/twisted/internet/defer.py:1934:50: error: Argument 1 to "_cancellableInlineCallbacks" has incompatible type
"Coroutine[Any, Any, Any] | GeneratorType[object, Never, object]"; expected
"Generator[Deferred[Any], object, Any] | Coroutine[Deferred[Any], object, Any]"  [arg-type]
                result = _cancellableInlineCallbacks(result)
                                                     ^~~~~~
src/twisted/internet/selectreactor.py:66:13: error: Value of type variable "_R" of "select" cannot be "_T" 
[type-var]
                select.select([selectable], [selectable], [selectable], 0)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/internet/selectreactor.py:66:13: error: Value of type variable "_W" of "select" cannot be "_T" 
[type-var]
                select.select([selectable], [selectable], [selectable], 0)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/internet/selectreactor.py:66:13: error: Value of type variable "_X" of "select" cannot be "_T" 
[type-var]
                select.select([selectable], [selectable], [selectable], 0)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:29:29: error: Name "NullVersioned" is not defined  [name-defined]
            pkcl = pickle.dumps(NullVersioned())
                                ^~~~~~~~~~~~~
src/twisted/test/test_persisted.py:61:14: error: Name "MyVersioned" is not defined  [name-defined]
            mv = MyVersioned()
                 ^~~~~~~~~~~
src/twisted/test/test_persisted.py:64:9: error: Name "MyVersioned" is not defined  [name-defined]
            MyVersioned.persistenceVersion = 4
            ^~~~~~~~~~~
src/twisted/test/test_persisted.py:86:14: error: Name "ClassWithCustomHash" is not defined  [name-defined]
            v1 = ClassWithCustomHash("v1", 0)
                 ^~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:87:14: error: Name "ClassWithCustomHash" is not defined  [name-defined]
            v2 = ClassWithCustomHash("v2", 0)
                 ^~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:91:9: error: Name "ClassWithCustomHash" is not defined  [name-defined]
            ClassWithCustomHash.persistenceVersion = 1
            ^~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:92: error: Unused "type: ignore" comment  [unused-ignore]
            ClassWithCustomHash.upgradeToVersion1 = lambda self: setattr(  # type: ignore[attr-defined]
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:92:9: error: Name "ClassWithCustomHash" is not defined  [name-defined]
            ClassWithCustomHash.upgradeToVersion1 = lambda self: setattr(  # type: ignore[attr-defined]
            ^~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:92:9: note: Error code "name-defined" not covered by "type: ignore[attr-defined]" comment
src/twisted/test/test_persisted.py:111:13: error: Name "ToyClassA" is not defined; did you mean "ToyClassB"? 
[name-defined]
            x = ToyClassA()
                ^~~~~~~~~
src/twisted/test/test_persisted.py:112:13: error: Name "ToyClassB" is not defined; did you mean "ToyClassA"? 
[name-defined]
            y = ToyClassB()
                ^~~~~~~~~
src/twisted/test/test_persisted.py:115:9: error: Name "ToyClassA" is not defined; did you mean "ToyClassB"? 
[name-defined]
            ToyClassA.persistenceVersion = 1
            ^~~~~~~~~
src/twisted/test/test_persisted.py:121: error: Unused "type: ignore" comment  [unused-ignore]
            ToyClassA.upgradeToVersion1 = upgradeToVersion1  # type: ignore[attr-defined]
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:121:9: error: Name "ToyClassA" is not defined  [name-defined]
            ToyClassA.upgradeToVersion1 = upgradeToVersion1  # type: ignore[attr-defined]
            ^~~~~~~~~
src/twisted/test/test_persisted.py:121:9: note: Error code "name-defined" not covered by "type: ignore[attr-defined]" comment
src/twisted/test/test_persisted.py:122:9: error: Name "ToyClassB" is not defined; did you mean "ToyClassA"? 
[name-defined]
            ToyClassB.persistenceVersion = 1
            ^~~~~~~~~
src/twisted/test/test_persisted.py:127: error: Unused "type: ignore" comment  [unused-ignore]
            ToyClassB.upgradeToVersion1 = setUpgraded  # type: ignore[attr-defined]
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/twisted/test/test_persisted.py:127:9: error: Name "ToyClassB" is not defined  [name-defined]
            ToyClassB.upgradeToVersion1 = setUpgraded  # type: ignore[attr-defined]
            ^~~~~~~~~
src/twisted/test/test_persisted.py:127:9: note: Error code "name-defined" not covered by "type: ignore[attr-defined]" comment
src/twisted/web/_stan.py:233:20: error: Incompatible return value type (got "GeneratorType[object, Never, object]",
expected "bytes | str | slot | CDATA | Comment | <8 more items>")  [return-value]
                return obj
                       ^~~
Found 21 errors in 4 files (checked 861 source files)
```

**Describe the solution you'd like**
The typing issues should  be fixed somehow before merging the upgrade.

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
I am testing on Ubuntu 26.04 using Python 3.14, but I set `--python-version 3.12` in tox.ini locally

**Comment by gudnimg** [comment]
I made an attempt to resolve these myself, and this is what I ended up with. I mostly concerned/unsure about `defer.py`. So far it seems like the typing was too strict.

[diff.txt](https://github.com/user-attachments/files/30201991/diff.txt)

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 2e23a8521f..65da8dd904 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -132,8 +132,8 @@ gtk-platform = [
 
 mypy = [
     "twisted[dev,all-non-platform]",
-    "mypy==2.1.0",
-    "mypy-zope==1.0.15",
+    "mypy==2.3.0",
+    "mypy-zope==1.0.16",
     "types-setuptools",
     "types-pyOpenSSL",
 ]
diff --git a/src/twisted/internet/defer.py b/src/twisted/internet/defer.py
index d88014215f..f6d9a9026f 100644
--- a/src/twisted/internet/defer.py
+++ b/src/twisted/internet/defer.py
@@ -1766,7 +1766,7 @@ class _CancellationStatus(Generic[_SelfResultT]):
 def _gotResultInlineCallbacks(
     r: object,
     waiting: list[Any],
-    gen: (Generator[Deferred[Any], Any, _T] | Coroutine[Deferred[Any], Any, _T]),
+    gen: (Generator[Any, Any, _T] | Coroutine[Any, Any, _T]),
     status: _CancellationStatus[_T],
     context: _Context,
 ) -> None:
@@ -1790,7 +1790,7 @@ def _gotResultInlineCallbacks(
 @_extraneous
 def _inlineCallbacks(
     result: object,
-    gen: (Generator[Deferred[Any], Any, _T] | Coroutine[Deferred[Any], Any, _T]),
+    gen: (Generator[Any, Any, _T] | Coroutine[Any, Any, _T]),
     status: _CancellationStatus[_T],
     context: _Context,
 ) -> None:
@@ -1998,7 +1998,7 @@ def _handleCancelInlineCallbacks(
 
 
 def _cancellableInlineCallbacks(
-    gen: (Generator[Deferred[Any], object, _T] | Coroutine[Deferred[Any], object, _T]),
+    gen: (Generator[Any, Any, _T] | Coroutine[Any, Any, _T]),
 ) -> Deferred[_T]:
     """
     Make an C{@}L{inlineCallbacks} cancellable.
diff --git a/src/twisted/internet/interfaces.py b/src/twisted/internet/interfaces.py
index 6cf273e460..23a10bd25c 100644
--- a/src/twisted/internet/interfaces.py
+++ b/src/twisted/internet/interfaces.py
@@ -1657,7 +1657,7 @@ class IFileDescriptor(ILoggingContext):
     An interface representing a UNIX-style numeric file descriptor.
     """
 
-    def fileno() -> object:
+    def fileno() -> int:
         """
         @return: The platform-specified representation of a file descriptor
             number.  Or C{-1} if the descriptor no longer has a valid file
diff --git a/src/twisted/internet/selectreactor.py b/src/twisted/internet/selectreactor.py
index 0e7235d0f5..8f282fd0ab 100644
--- a/src/twisted/internet/selectreactor.py
+++ b/src/twisted/internet/selectreactor.py
@@ -16,7 +16,12 @@ from typing import Callable, TypeVar
 from zope.interface import implementer
 
 from twisted.internet import posixbase
-from twisted.internet.interfaces import IReactorFDSet, IReadDescriptor, IWriteDescriptor
+from twisted.internet.interfaces import (
+    IFileDescriptor,
+    IReactorFDSet,
+    IReadDescriptor,
+    IWriteDescriptor,
+)
 from twisted.python import log
 from twisted.python.runtime import platformType
 
@@ -52,7 +57,7 @@ except ImportError:
 else:
     _extraBase = _ThreadedWin32EventsMixin
 
-_T = TypeVar("_T")
+_T = TypeVar("_T", bound=IFileDescriptor)
 
 
 def _onePreen(
diff --git a/src/twisted/test/test_persisted.py b/src/twisted/test/test_persisted.py
index e8b21edd43..60513994ba 100644
--- a/src/twisted/test/test_persisted.py
+++ b/src/twisted/test/test_persisted.py
@@ -20,7 +20,6 @@ from twisted.trial.unittest import TestCase
 
 class VersionTests(TestCase):
     def test_nullVersionUpgrade(self) -> None:
-        global NullVersioned
 
         class NullVersioned:
             def __init__(self) -> None:
@@ -39,7 +38,6 @@ class VersionTests(TestCase):
         assert mnv.ok, "initial upgrade not run!"
 
     def test_versionUpgrade(self) -> None:
-        global MyVersioned
 
         class MyVersioned(styles.Versioned):
             persistenceVersion = 2
@@ -73,7 +71,6 @@ class VersionTests(TestCase):
         assert obj.v4 == 1, "upgraded unnecessarily"
 
     def test_nonIdentityHash(self) -> None:
-        global ClassWithCustomHash
 
         class ClassWithCustomHash(styles.Versioned):
             def __init__(self, unique: str, hash: int) -> None:
@@ -100,7 +97,6 @@ class VersionTests(TestCase):
         self.assertTrue(v2.upgraded)
 
     def test_upgradeDeserializesObjectsRequiringUpgrade(self) -> None:
-        global ToyClassA, ToyClassB
 
         class ToyClassA(styles.Versioned):
             pass
diff --git a/src/twisted/web/_stan.py b/src/twisted/web/_stan.py
index 4075e1dd34..c9e003d791 100644
--- a/src/twisted/web/_stan.py
+++ b/src/twisted/web/_stan.py
@@ -230,7 +230,7 @@ class Tag:
                 "an exception in the future",
                 DeprecationWarning,
             )
-            return obj
+            return obj # type: ignore[return-value]
         elif iscoroutine(obj):
             warn(
                 "Cloning a Tag which contains a coroutine is unsafe, "

```

**Comment by glyph** [comment]
@gudnimg could you toss this up as a PR? It's a bit hard to work with the diff text here. (I think you're largely on the right track, though.)

**Comment by gudnimg** [comment]
> [@gudnimg](https://github.com/gudnimg) could you toss this up as a PR? It's a bit hard to work with the diff text here. (I think you're largely on the right track, though.)

Done. I probably won't look at this more until tomorrow.
