### ISSUE TITLE
twisted_iocpsupport: doesn't build with Python 3.13+

### ISSUE THREAD

**Issue by lazka** [twisted/twisted#12567]
**Describe the incorrect behavior you saw**

It doesn't build with Python 3.13+ as it uses functions that got removed in 3.13, see the build log here were the build errors are ignored:

https://github.com/twisted/twisted-iocpsupport/actions/runs/19028957141/job/54338306302#step:5:903

I assume this code is never tested with newer Python as it can't work and fails to build with clang for example.

I'm trying to package twisted downstream and here it fails like:

```c
clang -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -Wno-int-conversion -Wno-error=incompatible-pointer-types -Itwisted_iocpsupport -IC:/msys64/clang64/include/python3.13 -c twisted_iocpsupport/iocpsupport.c -o build/temp.mingw_x86_64_ucrt_llvm-cpython-313/twisted_iocpsupport/iocpsupport.o
twisted_iocpsupport/iocpsupport.c:1147:10: warning: non-portable path to file '"Python.h"'; specified path differs in case from file name on disk
      [-Wnonportable-include-path]
 1147 | #include "python.h"
      |          ^~~~~~~~~~
      |          "Python.h"
twisted_iocpsupport/iocpsupport.c:4868:15: error: call to undeclared function 'PyObject_AsReadBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 4868 |   __pyx_t_1 = PyObject_AsReadBuffer(__pyx_v_buff, (&__pyx_v_mem_buffer), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == ((int)-1))) __PYX_ERR(0, 255, __pyx_L1_error)
      |               ^
twisted_iocpsupport/iocpsupport.c:6500:15: error: call to undeclared function 'PyObject_AsWriteBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 6500 |   __pyx_t_1 = PyObject_AsWriteBuffer(__pyx_v_buff, (&__pyx_v_mem_buffer), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == ((int)-1))) __PYX_ERR(2, 15, __pyx_L1_error)
      |               ^
twisted_iocpsupport/iocpsupport.c:6500:15: note: did you mean 'PyObject_GetBuffer'?
C:/msys64/clang64/include/python3.13/pybuffer.h:46:17: note: 'PyObject_GetBuffer' declared here
   46 | PyAPI_FUNC(int) PyObject_GetBuffer(PyObject *obj, Py_buffer *view,
      |                 ^
twisted_iocpsupport/iocpsupport.c:6751:15: error: call to undeclared function 'PyObject_AsReadBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 6751 |   __pyx_t_1 = PyObject_AsReadBuffer(__pyx_v_buff, (&__pyx_v_mem_buffer), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == ((int)-1))) __PYX_ERR(2, 38, __pyx_L1_error)
      |               ^
twisted_iocpsupport/iocpsupport.c:7441:19: error: call to undeclared function 'PyObject_AsWriteBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 7441 |       __pyx_t_4 = PyObject_AsWriteBuffer(__pyx_t_1, ((void **)(&(__pyx_v_ws_buf[__pyx_v_i]).buf)), (&__pyx_v_size)); if (unlikely(__pyx_t_4 == ((int)-1))) __PYX...
      |                   ^
twisted_iocpsupport/iocpsupport.c:7823:15: error: call to undeclared function 'PyObject_AsWriteBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 7823 |   __pyx_t_1 = PyObject_AsWriteBuffer(__pyx_v_buff, ((void **)(&__pyx_v_ws_buf.buf)), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == ((int)-1))) __PYX_ERR(4, 47, __...
      |               ^
twisted_iocpsupport/iocpsupport.c:8216:15: error: call to undeclared function 'PyObject_AsReadBuffer'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 8216 |   __pyx_t_1 = PyObject_AsReadBuffer(__pyx_v_buff, ((void **)(&__pyx_v_ws_buf.buf)), (&__pyx_v_size)); if (unlikely(__pyx_t_1 == ((int)-1))) __PYX_ERR(5, 12, __p...
      |               ^
1 warning and 6 errors generated.
```

**Comment by glyph** [comment]
@lazka Yep, this looks like the problem is here https://github.com/twisted/twisted-iocpsupport/blob/e4d81ed027e64edf8d591be7966152c9bcfc9005/twisted_iocpsupport/iocpsupport.pyx#L56-L57

[From the docs for Python 3.12](https://docs.python.org/3.12/c-api/objbuffer.html): 

> These functions were part of the “old buffer protocol” API in Python 2. In Python 3, this protocol doesn’t exist anymore but the functions are still exposed to ease porting 2.x code.

So these APIs were deprecated in python 3, but the infrastructure for surfacing warnings is kind of busted all across the ecosystem and we weren't paying attention.

The solution is to replace these with `PyObject_GetBuffer` (although it might be worth investigating if cython has some support to make this easier, as I imagine "buffer protocol" is a popular use-case for cython?). Luckily it's only a few lines of code in wsasend.pxi/wsarecv.pxi so it shouldn't be too huge of a project if someone has a bit of time.
