### ISSUE TITLE
iocpsupport.c does not compile on python 3.7

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9501]
|<img alt="doughishere's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| doughishere reported|
|-|-|
|Trac ID|trac#9501|
|Type|enhancement|
|Created|2018-07-29 13:38:53Z|
|Branch|https://github.com/twisted/twisted/tree/9501-cython-regen|

```
9: 'exc_value': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7690): error C203
9: 'exc_traceback': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7697): error C203
9: 'exc_type': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7698): error C203
9: 'exc_value': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7699): error C203
9: 'exc_traceback': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7700): error C203
9: 'exc_type': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7701): error C203
9: 'exc_value': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7702): error C203
9: 'exc_traceback': is not a member of '_ts'
    c:\python3.7\include\pystate.h(209): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Buil
dTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2

    ----------------------------------------
Command "c:\python3.7\python.exe -u -c "import setuptools, tokenize;__file__='C:
\\Users\\1\\AppData\\Local\\Temp\\pip-install-e8r4ny20\\twisted\\setup.py
';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n'
);f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\~1\AppData\Local\Temp\pip-record-jfq_y0x0\install-record.txt --single-version
-externally-managed --compile" failed with error code 1 in C:\Users\\App
Data\Local\Temp\pip-install-e8r4ny20\twisted\
```

Im trying to install channels and this keeps breaking my pip.

<details><summary>Searchable metadata</summary>

```
trac-id__9501 9501
type__enhancement enhancement
reporter__doughishere doughishere
priority__highest highest
milestone__Python_3_7_support Python 3.7 support
branch__9501_cython_regen 9501-cython-regen
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1532871533295835 1532871533295835
changetime__1536226990659135 1536226990659135
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

Milestone renamed

**Comment by twisted-trac** [comment]
|[<img alt="rodionkvashnin's avatar" src="https://avatars.githubusercontent.com/u/25197200?s=50" width="50" height="50">](https://github.com/rodionkvashnin)<a name="note_7"></a>|@rodionkvashnin commented|
|-|-|

This is due to the fact that iocpsupport.c is generated by the old version of Cython that does not support Python 3.7. Need to generate iocpsupport.c with the new version of Cython.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Thanks for investigating, Rodion!

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_9"></a>|@hawkowl commented|
|-|-|

See: https://github.com/twisted/twisted/pull/1050

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph set owner to @hawkowl|
|-|-|

it looks like you did the thing, so, thanks for doing it.

really the challenge here is getting CI to agree that you did it; once you've done that, please land.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_11"></a>|@hawkowl set status to `closed`|
|-|-|

In changeset dbf6d35b5c9d1b380f7a334df9db8b72fce92970
```
#!CommitTicketReference repository="" revision="dbf6d35b5c9d1b380f7a334df9db8b72fce92970"
Merge 9501-cython-regen: Regenerate our Cython

Author: hawkowl
Reviewer: glyph
Fixes: ticket:9501
```
