### PR TITLE
test_shellcomp.py now works on python 3

### PR DESCRIPTION
**Pull request by acabhishek942**
See : http://twistedmatrix.com/trac/ticket/8586

### CODE REVIEW

File: twisted/python/dist3.py [hunk 1]
```diff
@@ -388,6 +388,7 @@
     "twisted.python.test.test_dist3",
     "twisted.python.test.test_runtime",
     "twisted.python.test.test_sendmsg",
+    "twisted.python.test.test_shellcomp"
```
Comment (adiroiban) [inline twisted/python/dist3.py]: you forgot the comma at the end

**Comment by rodrigc** [comment]
If I ran this command:

```
tox -e py35-tests twisted/python/test/test_shellcomp.py
```

or

```
tox -e py35-tests twisted.python.test.test_shellcomp
```

then I get this error:

```
  File "../../../twisted/python/test/test_shellcomp.py", line 14, in <module>
    from twisted.python import _shellcomp, usage, reflect
builtins.ImportError: cannot import name '_shellcomp'
```

In twisted/python/dist3.py , you need to add:

```
"twisted.python._shellcomp",
```

to the modules variable.

File: twisted/python/_shellcomp.py [hunk 2]
```diff
@@ -350,16 +351,17 @@ def writeHeader(self):
         This is the start of the code that calls _arguments
         @return: L{None}
         """
-        self.file.write('#compdef %s\n\n'
-                        '_arguments -s -A "-*" \\\n' % (self.cmdName,))
+        self.file.write(b'#compdef %s\n\n'
+                        b'_arguments -s -A "-*" \\\n'
+                        % self.cmdName.encode('utf-8'))
```
Comment (rodrigc) [inline twisted/python/_shellcomp.py]: The build works on Python 2.7 and Python 3.5, but it fails on Python 3.3 and Python 3.4 here:

https://travis-ci.org/twisted/twisted/jobs/144663141#L2296

That is because % formatting for bytes was not implemented until Python 3.5 : https://www.python.org/dev/peps/pep-0461/

To move this along and get it working on Python 3.3 and Python 3.4, I suggest that you
not use % formatting here.

File: twisted/python/_shellcomp.py [hunk 3]
```diff
@@ -174,11 +174,12 @@ def write(self, genSubs=True):
...
             gen.extraActions.insert(0, SubcommandAction())
             gen.write()
-            self.file.write('local _zsh_subcmds_array\n_zsh_subcmds_array=(\n')
+            self.file.write(b'local _zsh_subcmds_array\n_zsh_subcmds_array=(\n')
             for (cmd, short, parser, desc) in self.options.subCommands:
-                self.file.write('"%s:%s"\n' % (cmd, desc))
-            self.file.write(")\n\n")
-            self.file.write('_describe "sub-command" _zsh_subcmds_array\n')
+                self.file.write(
+                    b'"%s:%s"\n' % (cmd.encode('utf-8'), desc.encode('utf-8')))
```
Comment (rodrigc) [inline twisted/python/_shellcomp.py]: The build on Python 3.3 and Python 3.4 is failing here: https://travis-ci.org/twisted/twisted/jobs/144688549#L2298 .  You need to get rid of % formatting here also

**Comment by rodrigc** [comment]
Moved to https://github.com/twisted/twisted/pull/333
