### ISSUE TITLE
iocpreactor.c linker errors on Python 3.2 msvc9

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4926]
|<img alt="Tourman's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Tourman reported|
|-|-|
|Trac ID|trac#4926|
|Type|defect|
|Created|2011-03-06 22:10:37Z|
|Branch|https://github.com/twisted/twisted/tree/4926-rodrigc-iocp-py3|

After applying patches from tickets [#4244](https://github.com/twisted/twisted/issues/4244), [#4246](https://github.com/twisted/twisted/issues/4246), [#4247](https://github.com/twisted/twisted/issues/4247) and [#4555](https://github.com/twisted/twisted/issues/4555), I get linker errors from iocsupport.c

```
"iocpsupport.obj : error LNK2019: unresolved external symbol _PyString_FromString
AndSize referenced in function ___pyx_f_11iocpsupport__makesockaddr
iocpsupport.obj : error LNK2019: unresolved external symbol _PyString_FromString
 referenced in function ___pyx_f_11iocpsupport__makesockaddr
iocpsupport.obj : error LNK2019: unresolved external symbol _PyString_AsString r
eferenced in function ___pyx_f_11iocpsupport_fillinetaddr
iocpsupport.obj : error LNK2019: unresolved external symbol _PyBuffer_New refere
nced in function ___pyx_pf_11iocpsupport_1AllocateReadBuffer
build\lib.win32-3.2\twisted\internet\iocpreactor\iocpsupport.pyd : fatal error LNK1120: 4 unresolved externals"
```

Now, the PyString errors are a simple fix, by using PyUnicode (see attached patch), but PyBuff_New has been removed in Python 3.x, and from what I can see it's a bit more of a complicated fix. I used Cython 0.14.1 to compile the new code.

Python docs covering the new buffer: [http://docs.python.org/release/3.2/c-api/buffer.html]

Attachments:

* [iocpsupport.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/0c6/0c6da8812bc2c3c3b5fec60ac1c51ee06b3048c0/cc239126448b7390c00389362e850b98b9982fcf.diff) (1770 bytes) - added by Tourman on 2011-03-06 22:11:28Z - patch for iocpsupport.pyx
* [iocpsupport.2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/0c6/0c6da8812bc2c3c3b5fec60ac1c51ee06b3048c0/ebc7ff557a5d93f5039352147c1f3f75668381bd.diff) (1760 bytes) - added by Tourman on 2011-03-18 18:52:11Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4926 4926
type__defect defect
reporter__Tourman Tourman
priority__normal normal
milestone__Python_3_x Python-3.x
branch__4926_rodrigc_iocp_py3 4926-rodrigc-iocp-py3
branch_author__Tourman Tourman
status__closed closed
resolution__fixed fixed
component__core core
keywords__None None
time__1299449437000000 1299449437000000
changetime__1468272489897551 1468272489897551
version__None None
owner__rodrigc rodrigc
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

(In [31092]) Branching to 'iocpreactor-3.x-4926'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

(In [31093]) Apply patch

refs [#4926](https://github.com/twisted/twisted/issues/4926)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun removed owner<br>@exarkun set status to `new`|
|-|-|

Eh, this requires more Windows access than I realized and than I have, I can't quite review it.

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|PenguinOfDoom commented|
|-|-|

Thank you for submitting the patch.

I don't think PyUnicode* are the correct functions to use. The socket API expects ASCII strings, not Unicode.

What is the Python 3 replacement for PyBuffer_New?

**Comment by twisted-trac** [comment]
|<img alt="Tourman's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|Tourman commented|
|-|-|

Replying to [PenguinOfDoom](#note_6):
> Thank you for submitting the patch.
> 
> I don't think PyUnicode* are the correct functions to use. The socket API expects ASCII >strings, not Unicode.

There is only PyUnicode and PyBytes objects in Python 3.x - you can encode strings as ascii, but the PyString objects have been removed. 

See: http://docs.python.org/release/3.2/howto/cporting.html

>What is the Python 3 replacement for PyBuffer_New?
Looking over the documentation, it appears that you need to fill a Py_buffer structure, and use the PyObject_GetBuffer or PyObject_CopyToObject functions.

I have yet to use this API, so this is what I gather from the documentation.

**Comment by twisted-trac** [comment]
|<img alt="PenguinOfDoom's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_8"></a>|PenguinOfDoom set owner to facundobatista|
|-|-|

Facundo, you seem to be interested in Python 3 support. Welcome to the project :)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

> expects ASCII strings

This should be _byte_ strings, of course.

Also I believe PenguinOfDoom meant to remove the review keyword, as he did point out some issues with the presently attached patch.

**Comment by twisted-trac** [comment]
|<img alt="Tourman's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|Tourman commented|
|-|-|

Replying to [exarkun](#note_9):
> > expects ASCII strings
> 
> This should be _byte_ strings, of course.
> 
> Also I believe PenguinOfDoom meant to remove the review keyword, as he did point out some issues with the presently attached patch.

Attached changes using PyBytes, let me know if this is OK.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

Python 2.x doesn't have the `PyBytes_` APIs, so this change breaks IOCP reactor on Python 2.x.  We can't do that quite yet.  The code needs to work on Python 2.5 though Python 2.7 _and_ Python 3.2.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_12"></a>|@thijstriemstra commented|
|-|-|

Replying to [exarkun](#note_11):
> The code needs to work on Python 2.5 though Python 2.7 _and_ Python 3.2.

I believe this requirement has now changed to "Python 2.6 through 2.7 and Python 3.3".

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_13"></a>|@rodrigc commented|
|-|-|

After [ticket:8017] the requirement is Python 2.7 and Python >= 3.3

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)|@rodrigc removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_15"></a>|@rodrigc commented|
|-|-|

See:
https://github.com/twisted/twisted/pull/301

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_16"></a>|@adiroiban commented|
|-|-|

Is the coverage report broken? I see little coverage for these changes.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_17"></a>|@rodrigc commented|
|-|-|

I do not know much about codecov or why it is broken.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_18"></a>|@adiroiban set owner to @rodrigc|
|-|-|

Ok. That is fine. When asking for a review please also add notes about all the know issues, such as broken coverage or broken builder or missing builders.

Windows 2.7 coverage reporting should be now fixed by using the Windows Server 2012R2 slave.

Twisted with Python3 on Windows, is still an unsupported platform.

I am now working to fix the py3+win builder using the new Win2012 slave. 

I have created a py3.5 builder on Windows 
https://buildbot.twistedmatrix.com/builders/win2012r2-py3.5/builds/1

I can see that the extension is built, but now there are 18 new warnings.


You can use this builder to trigger py3.5 builds on Windows for this branch.

https://buildbot.twistedmatrix.com/builders/win2012r2-py3.5

--------

Python 2.7 test and coverage looks good so I think that we care close to merging this branch.

Can you please look at how can we fix the new warnings?

It would be nice to have a clean build. If the warning can not be fixed, please document why they can not be fixed.


Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_19"></a>|@rodrigc removed owner|
|-|-|

I fixed a few simple C compiler warnings with Visual C++ 2015.
The ones that are left are OK.
* there are a few warnings left about deprecated C API's according to Visual C++ 2015.  These warnings are harmless.  Addressing these warnings by changing the code is a fair bit of work.  I tried to do it a bit and broke the tests, so I stopped tis effort.
* there are some existing warnings that cannot be avoided because we interchangeably use
  DWORD which is "unsigned long" and HANDLE which is "void *".  Technically this works,
  but the compiler complains.  I took a whack at trying to eliminate all these warnings,
  and it wasn't simple, and I broke the tests, so I stopped this effort.

The patch that is in the branch is OK.  It builds on Python2 and Python3.
Tests pass on Python2.  Getting tests to pass on Python3 will be more follow on work.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_20"></a>|@adiroiban commented|
|-|-|

Thanks.

We have similar warnings in trunk on Python 2.7 

https://buildbot.twistedmatrix.com/builders/windows7-64-py2.7-coverage/builds/788/steps/compile/logs/warnings%20%2812%29

so I think that the warnings are fine.

-------------

Why are you saying that it needs more work to get the tests to pass on python 3?


I can see that both tcp and udp code has some coverage, at least for the happy flow.

Is there a follow up ticket?

The topfile of this branch says that iocp reactor is now ported on python 3, that should imply that all iocp tests are passing on python 3.

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_21"></a>|@rodrigc commented|
|-|-|

Until I have a usable trial and tox environment for testing Windows and Python 3,
it is very difficult for me to gauge where things are, but I am definitely making progress.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_22"></a>|@adiroiban set owner to @rodrigc|
|-|-|

Changes look good.

The scope if this ticket is to fix the linker errors, and I think that this is done.

In this build I can see that it compiles ok on python 3.5 https://buildbot.twistedmatrix.com/builders/win2012r2-64-py3.5/builds/3

Since the tests are not executed on python3 I am not comfortable with advertising this being ported on Windows + python3.

I would suggest merge this branch with a .misc and to create a follow up ticket in which we check that iocp tests are succesfully running on Py3 + Windows and then we can tell the worlds that iocp is ported on python3.

Please check my comments and if you are happy with my suggestion, please merge. Otherwise please put it back for review.

Thanks!

**Comment by twisted-trac** [comment]
|<img alt="GitHub's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_23"></a>|GitHub set status to `closed`|
|-|-|

In changeset ebcabbbba6bc899a9f8729a67a41a3f925a219b2
```
#!CommitTicketReference repository="" revision="ebcabbbba6bc899a9f8729a67a41a3f925a219b2"
Merge pull request #301 from twisted/4926-rodrigc-iocp-py3

Author: rodrigc
Reviewer: adiroiban
Fixes: #4926

Eliminate Windows iocp compilation errors on Python 3
```
